version: '3'

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - .ssql.cnf:/etc/mysql/my.cnf
    networks:
      - ja

  frontend:
    build:
      context: ./frontend/
    restart: always
    ports:
      - "8080:3000"
    environment:
      VIRTUAL_HOST: "ja.mylittlepwnies.tech"
      LETSENCRYPT_HOST: "ja.mylittlepwnies.tech"
      VIRTUAL_PORT: 8080
    networks:
      - ja
      - ssl-project
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/
      args:
          DBUSER: ${MYSQL_USER}
          DBPASS: ${MYSQL_PASSWORD}
          DATABASE: ${MYSQL_DATABASE}
    restart: always
    ports:
      - "6969:6969"
    environment:
      DATABASE: ${MYSQL_DATABASE}
      DBUSER: ${MYSQL_USER}
      DBPASS: ${MYSQL_PASSWORD}
      VIRTUAL_HOST: "ja.mylittlepwnies.tech"
      LETSENCRYPT_HOST: "ja.mylittlepwnies.tech"
      VIRTUAL_PORT: 6969
    networks:
      - ja
      - ssl-project
    depends_on:
      - db

volumes:
  db_data:

networks:
  ja:
    external: true
  ssl-project:
    external: true
