version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/var/lib/mysql/init.sql
    command: --init-file /var/lib/mysql/init.sql

  backend:
    build: ./backend/
    restart: always
    ports:
      - "6969:6969"

  frontend:
    build: ./frontend/
    restart: always
    ports:
      - "80:80"

volumes:
  db_data:

