version: '3'

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - .ssql.cnf:/etc/mysql/my.cnf
    networks:
      - ja

  frontend:
    build:
      context: ./frontend/
    restart: always
    environment:
      VIRTUAL_HOST: "ja.mylittlepwnies.tech"
      LETSENCRYPT_HOST: "ja.mylittlepwnies.tech"
      VIRTUAL_PORT: 3000
    networks:
      - ja
      - ssl-project
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/
      args:
          DBUSER: ${MYSQL_USER}
          DBPASS: ${MYSQL_PASSWORD}
          DATABASE: ${MYSQL_DATABASE}
    restart: always
    environment:
      DATABASE: ${MYSQL_DATABASE}
      DBUSER: ${MYSQL_USER}
      DBPASS: ${MYSQL_PASSWORD}
      VIRTUAL_PORT: 6969
      VIRTUAL_HOST: japi.oppaiweeb.tech
      LETSENCRYPT_HOST: japi.oppaiweeb.tech
    networks:
      - ja
      - ssl-project
    depends_on:
      - db

volumes:
  db_data:

networks:
  ja:
    external: false
  ssl-project:
    external: true
