version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ja
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: ./backend/
      args:
          DBUSER: ${MYSQL_USER}
          DBPASS: ${MYSQL_PASSWORD}
          DATABASE: ${MYSQL_DATABASE}

    restart: always
    ports:
      - "6969:6969"
    environment:
      DATABASE: ${MYSQL_DATABASE}
      DBUSER: ${MYSQL_USER}
      DBPASS: ${MYSQL_PASSWORD}
    networks:
      - ja
    depends_on:
        db

volumes:
  db_data:

networks:
  ja:
    external: false
